apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ values.Image.WebServiceName }}
  name: {{ values.Image.WebServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: 3030-3030
    port: 3030
    protocol: TCP
    targetPort: 3030
  selector:
    app: {{ values.Image.WebServiceName }}
  type: LoadBalancer
  Pods:
    - name: {{ values.Release.Name }}
      image: {{ values.Image.Webimage }}
      ports:
        - containerPort: 3030
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ values.Image.AppServiceName }}
  name: {{ values.Image.AppServiceName }}
  namespace: {{ values.Release.Namespace }}
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ values.Image.AppServiceName }}
  type: LoadBalancer
  Pods:
    - name: {{ values.Release.Name }}
      image: {{ values.Image.Appimage }}
      ports:
        - containerPort: 3030
          protocol: TCP
